spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/star_wars?useTimezone=true&serverTimezone=UTC
    username: root
    password: leid2012
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      jdbc:
    generate-ddl: true
